# Form implementation generated from reading ui file 'ui/Live.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Match(object):
    def setupUi(self, Match):
        Match.setObjectName("Match")
        Match.resize(747, 670)
        self.columnView = QtWidgets.QColumnView(Match)
        self.columnView.setGeometry(QtCore.QRect(230, 30, 301, 431))
        self.columnView.setObjectName("columnView")
        self.label = QtWidgets.QLabel(Match)
        self.label.setGeometry(QtCore.QRect(50, 50, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Match)
        self.label_2.setGeometry(QtCore.QRect(580, 40, 101, 20))
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(Match)
        self.lcdNumber.setGeometry(QtCore.QRect(60, 120, 64, 121))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Match)
        self.lcdNumber_2.setGeometry(QtCore.QRect(590, 120, 64, 121))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.pushButton = QtWidgets.QPushButton(Match)
        self.pushButton.setGeometry(QtCore.QRect(100, 550, 141, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Match)
        QtCore.QMetaObject.connectSlotsByName(Match)

    def retranslateUi(self, Match):
        _translate = QtCore.QCoreApplication.translate
        Match.setWindowTitle(_translate("Match", "Dialog"))
        self.label.setText(_translate("Match", "Home Team"))
        self.label_2.setText(_translate("Match", "Guest Team"))
        self.pushButton.setText(_translate("Match", "Finish Match"))
