# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 744)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.matchPlan = QtWidgets.QListWidget(self.centralwidget)
        self.matchPlan.setGeometry(QtCore.QRect(161, 131, 256, 192))
        self.matchPlan.setMaximumSize(QtCore.QSize(1113, 16777215))
        self.matchPlan.setObjectName("matchPlan")
        self.finish_tournament = QtWidgets.QPushButton(self.centralwidget)
        self.finish_tournament.setGeometry(QtCore.QRect(160, 550, 115, 25))
        self.finish_tournament.setObjectName("finish_tournament")
        self.contestor_label = QtWidgets.QLabel(self.centralwidget)
        self.contestor_label.setGeometry(QtCore.QRect(9, 108, 62, 17))
        self.contestor_label.setObjectName("contestor_label")
        self.tournament_parameters = QtWidgets.QPushButton(self.centralwidget)
        self.tournament_parameters.setGeometry(QtCore.QRect(9, 9, 146, 25))
        self.tournament_parameters.setObjectName("tournament_parameters")
        self.teams_and_schedule = QtWidgets.QPushButton(self.centralwidget)
        self.teams_and_schedule.setGeometry(QtCore.QRect(9, 46, 124, 25))
        self.teams_and_schedule.setObjectName("teams_and_schedule")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(161, 108, 63, 17))
        self.label.setObjectName("label")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(770, 40, 181, 131))
        self.logoLabel.setObjectName("logoLabel")
        self.start_match = QtWidgets.QPushButton(self.centralwidget)
        self.start_match.setGeometry(QtCore.QRect(160, 340, 171, 25))
        self.start_match.setObjectName("start_match")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.finish_tournament.setText(_translate("MainWindow", "Finish Tournament"))
        self.contestor_label.setText(_translate("MainWindow", "Contestors"))
        self.tournament_parameters.setText(_translate("MainWindow", "Tournament Parameters"))
        self.teams_and_schedule.setText(_translate("MainWindow", "Teams and Schedule"))
        self.label.setText(_translate("MainWindow", "Match Plan"))
        self.logoLabel.setText(_translate("MainWindow", "TextLabel"))
        self.start_match.setText(_translate("MainWindow", "Start next match"))
