# Form implementation generated from reading ui file 'ui/match_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Match_Dialog(object):
    def setupUi(self, Match_Dialog):
        Match_Dialog.setObjectName("Match_Dialog")
        Match_Dialog.resize(1116, 989)
        self.buttonBox = QtWidgets.QDialogButtonBox(Match_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(780, 90, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.home_team = QtWidgets.QListWidget(Match_Dialog)
        self.home_team.setGeometry(QtCore.QRect(100, 100, 231, 291))
        self.home_team.setObjectName("home_team")
        self.visiting_team = QtWidgets.QListWidget(Match_Dialog)
        self.visiting_team.setGeometry(QtCore.QRect(340, 100, 241, 291))
        self.visiting_team.setObjectName("visiting_team")
        self.home_score = QtWidgets.QLCDNumber(Match_Dialog)
        self.home_score.setGeometry(QtCore.QRect(170, 400, 121, 71))
        self.home_score.setObjectName("home_score")
        self.visiting_score = QtWidgets.QLCDNumber(Match_Dialog)
        self.visiting_score.setGeometry(QtCore.QRect(390, 400, 131, 71))
        self.visiting_score.setObjectName("visiting_score")
        self.home_label = QtWidgets.QLabel(Match_Dialog)
        self.home_label.setGeometry(QtCore.QRect(100, 70, 54, 17))
        self.home_label.setObjectName("home_label")
        self.visiting_label = QtWidgets.QLabel(Match_Dialog)
        self.visiting_label.setGeometry(QtCore.QRect(350, 70, 111, 17))
        self.visiting_label.setObjectName("visiting_label")
        self.live_table = QtWidgets.QListWidget(Match_Dialog)
        self.live_table.setGeometry(QtCore.QRect(30, 530, 491, 361))
        self.live_table.setObjectName("live_table")
        self.scorer_list = QtWidgets.QListWidget(Match_Dialog)
        self.scorer_list.setGeometry(QtCore.QRect(680, 530, 256, 361))
        self.scorer_list.setObjectName("scorer_list")

        self.retranslateUi(Match_Dialog)
        self.buttonBox.accepted.connect(Match_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Match_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Match_Dialog)

    def retranslateUi(self, Match_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Match_Dialog.setWindowTitle(_translate("Match_Dialog", "Dialog"))
        self.home_label.setText(_translate("Match_Dialog", "TextLabel"))
        self.visiting_label.setText(_translate("Match_Dialog", "TextLabel"))
