# Form implementation generated from reading ui file 'ui/parameter.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_parameter(object):
    def setupUi(self, parameter):
        parameter.setObjectName("parameter")
        parameter.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        parameter.resize(583, 300)
        parameter.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(parameter)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tournamentName = QtWidgets.QLineEdit(parameter)
        self.tournamentName.setGeometry(QtCore.QRect(130, 10, 391, 23))
        self.tournamentName.setObjectName("tournamentName")
        self.nameLabel = QtWidgets.QLabel(parameter)
        self.nameLabel.setGeometry(QtCore.QRect(30, 20, 62, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.label_5 = QtWidgets.QLabel(parameter)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_5.setObjectName("label_5")
        self.startTime = QtWidgets.QTimeEdit(parameter)
        self.startTime.setGeometry(QtCore.QRect(130, 70, 118, 24))
        self.startTime.setObjectName("startTime")
        self.match_duration = QtWidgets.QSpinBox(parameter)
        self.match_duration.setGeometry(QtCore.QRect(190, 120, 41, 24))
        self.match_duration.setObjectName("match_duration")
        self.intermission = QtWidgets.QSpinBox(parameter)
        self.intermission.setGeometry(QtCore.QRect(190, 160, 41, 24))
        self.intermission.setObjectName("intermission")
        self.label_2 = QtWidgets.QLabel(parameter)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 161, 20))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parameter)
        self.label.setGeometry(QtCore.QRect(20, 120, 111, 20))
        self.label.setObjectName("label")

        self.retranslateUi(parameter)
        self.buttonBox.accepted.connect(parameter.accept) # type: ignore
        self.buttonBox.rejected.connect(parameter.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(parameter)

    def retranslateUi(self, parameter):
        _translate = QtCore.QCoreApplication.translate
        parameter.setWindowTitle(_translate("parameter", "Tournament Parameters"))
        self.nameLabel.setText(_translate("parameter", "Name"))
        self.label_5.setText(_translate("parameter", "Start Time"))
        self.label_2.setText(_translate("parameter", "Break between matches"))
        self.label.setText(_translate("parameter", "Match duration"))
