# Form implementation generated from reading ui file 'ui/team_members.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(824, 626)
        self.roaster_yes_no = QtWidgets.QDialogButtonBox(Dialog)
        self.roaster_yes_no.setGeometry(QtCore.QRect(-20, 540, 341, 32))
        self.roaster_yes_no.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.roaster_yes_no.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.roaster_yes_no.setObjectName("roaster_yes_no")
        self.member_list = QtWidgets.QTableWidget(Dialog)
        self.member_list.setGeometry(QtCore.QRect(10, 50, 541, 381))
        self.member_list.setObjectName("member_list")
        self.member_list.setColumnCount(4)
        self.member_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.member_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.member_list.setHorizontalHeaderItem(3, item)
        self.team_name = QtWidgets.QLabel(Dialog)
        self.team_name.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.team_name.setObjectName("team_name")
        self.add_player = QtWidgets.QPushButton(Dialog)
        self.add_player.setGeometry(QtCore.QRect(560, 210, 251, 25))
        self.add_player.setObjectName("add_player")
        self.input_name = QtWidgets.QLineEdit(Dialog)
        self.input_name.setGeometry(QtCore.QRect(650, 120, 113, 25))
        self.input_name.setObjectName("input_name")
        self.input_surname = QtWidgets.QLineEdit(Dialog)
        self.input_surname.setGeometry(QtCore.QRect(650, 150, 113, 25))
        self.input_surname.setObjectName("input_surname")
        self.input_id = QtWidgets.QLineEdit(Dialog)
        self.input_id.setGeometry(QtCore.QRect(650, 90, 41, 25))
        self.input_id.setObjectName("input_id")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(570, 120, 61, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(570, 150, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(570, 90, 54, 17))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.roaster_yes_no.accepted.connect(Dialog.accept) # type: ignore
        self.roaster_yes_no.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.member_list.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nummer"))
        item = self.member_list.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Vorname"))
        item = self.member_list.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Nachname"))
        item = self.member_list.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Tore"))
        self.team_name.setText(_translate("Dialog", "TextLabel"))
        self.add_player.setText(_translate("Dialog", "Hinzufügen"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_2.setText(_translate("Dialog", "Nachname"))
        self.label_3.setText(_translate("Dialog", "Nummer"))
